# Generated by Django 4.2.7 on 2023-11-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empresa_alter_cliente_id_arriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='dias',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='costo_diario',
            field=models.BigIntegerField(default=0),
        ),
    ]
