# Generated by Django 4.2.7 on 2023-11-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_arriendo_dias_alter_arriendo_costo_diario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='arriendos', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='arriendos', to='api.empresa'),
        ),
    ]
